[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Balethon"
version = "0.1.2"
description = "Asynchronous library for creating bots in the Bale messenger"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Sajjad", email = "sajjadalipour2006@gmail.com"},
  {name = "Abolfazl Amiri", email = "soltshen@gmail.com"}
]
keywords = ["bale", "messenger", "bot", "api", "client"]
classifiers = [
    "Framework :: aiohttp",
    "License :: OSI Approved :: MIT License"
]
dependencies = ["aiohttp==3.8.4"]

[project.urls]
"Homepage" = "https://github.com/SajjadAlipour2006/Balethon"
"Tracker" = "https://github.com/SajjadAlipour2006/Balethon/issues"
"Community" = "https://t.me/balethon_group"